apiVersion: v1
kind: Pod
metadata:
  name: db-noticias
  labels:
    name: alura
    app: db-noticias-pod
spec:
  containers:
  - name: container-db-noticias
    image: aluracursos/mysql-db:1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
     - containerPort: 3306
    env:
      - name: "MYSQL_ROOT_PASSWORD"
        value: "q1w2e3r4"
      - name: "MYSQL_DATABASE"
        value: "empresa"  
      - name: "MYSQL_PASSWORD"
        value: "q1w2e3r4"